<?php
	$this->load->model('MenuModel');
	$this->load->model('ContactModel');
	$this->load->model('SocialModel');
	$this->load->model('ContentModel');
	$this->load->helper('text');
	$this->load->view('inc/header_front.php');
	$this->load->view($main_content);
	$this->load->view('inc/footer_front.php');
?>